env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - react
  - jest
rules: {
<<<<<<< HEAD
  "react/jsx-one-expression-per-line": [0],
  "react/prop-types": [0],
  "import/extensions": [ 2, "ignorePackages"]
=======
    "react/jsx-one-expression-per-line": [0],
    "react/prop-types": [0],
    "import/extensions": [2, "ignorePackages"]
>>>>>>> modal-test
}
