env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - react
rules: {
    "react/jsx-one-expression-per-line": [<enabled>, { "allow": "single-child" }]
}
