env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules: {
    "react/jsx-one-expression-per-line": [0],
    "react/prop-types": [0],
    "import/extensions": [2, "ignorePackages"]
}
