env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - react
rules: {
    "react/jsx-one-expression-per-line": [1, { "allow": "single-child" }]
    "react/prop-types": [0],
    "import/extensions": [2, "ignorePackages"]
}
